/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SystemContractErrors } from "./SystemContractErrors";
export type { TestSystemContract } from "./TestSystemContract";
