/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ethZetaMockSol from "./EthZetaMock.sol";
export type { ethZetaMockSol };
import type * as zetaConnectorMockSol from "./ZetaConnectorMock.sol";
export type { zetaConnectorMockSol };
export type { SwapHelperLib } from "./SwapHelperLib";
export type { TestSystemContract } from "./TestSystemContract";
export type { TestZRC20 } from "./TestZRC20";
