/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SwapHelperLibInterface extends Interface {
  getFunction(
    nameOrSignature: "getMinOutAmount" | "uniswapv2PairFor"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMinOutAmount",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapv2PairFor",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMinOutAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapv2PairFor",
    data: BytesLike
  ): Result;
}

export interface SwapHelperLib extends BaseContract {
  connect(runner?: ContractRunner | null): SwapHelperLib;
  waitForDeployment(): Promise<this>;

  interface: SwapHelperLibInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMinOutAmount: TypedContractMethod<
    [
      router: AddressLike,
      zrc20: AddressLike,
      target: AddressLike,
      amountIn: BigNumberish
    ],
    [bigint],
    "view"
  >;

  uniswapv2PairFor: TypedContractMethod<
    [factory: AddressLike, tokenA: AddressLike, tokenB: AddressLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMinOutAmount"
  ): TypedContractMethod<
    [
      router: AddressLike,
      zrc20: AddressLike,
      target: AddressLike,
      amountIn: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "uniswapv2PairFor"
  ): TypedContractMethod<
    [factory: AddressLike, tokenA: AddressLike, tokenB: AddressLike],
    [string],
    "view"
  >;

  filters: {};
}
