version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies"
    allow:
      - dependency-name: "@zetachain/networks"
      - dependency-name: "@zetachain/protocol-contracts"
      - dependency-name: "@zetachain/addresses"
