[profile.default]
src = 'contracts'
fs_permissions = [{ access = "read", path = "./node_modules" }]
via_ir = false
optimizer = true
optimizer_runs = 200
auto_detect_solc = true
libs = ["node_modules", "lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]
