/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as izrc20Sol from "./IZRC20.sol";
export type { izrc20Sol };
export type { IERC20 } from "./IERC20";
export type { IWETH } from "./IWETH";
