<<<<<<< HEAD
[profile.default]
src = 'contracts'
out = 'out'
viaIR = true
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
verbosity = 3

[dependencies]
forge-std = { version = "1.9.2" }
=======
[profile.default]
src = 'contracts'
out = 'out'
viaIR = true
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
verbosity = 3

[dependencies]
forge-std = { version = "1.9.2" }
>>>>>>> 5f253fe3f9f992f7f918f140b466e2635ecd8c54
