/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as errorsSol from "./Errors.sol";
export type { errorsSol };
import type * as revertSol from "./Revert.sol";
export type { revertSol };
import type * as evm from "./evm";
export type { evm };
import type * as zevm from "./zevm";
export type { zevm };
