/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  BytesHelperLib,
  BytesHelperLibInterface,
} from "../../contracts/BytesHelperLib";

const _abi = [
  {
    inputs: [],
    name: "OffsetOutOfBounds",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220766c094da1789d965b537afc578d9d0e9a34b2290ca8a52d0bb141f2642765b964736f6c63430008070033";

type BytesHelperLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BytesHelperLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BytesHelperLib__factory extends ContractFactory {
  constructor(...args: BytesHelperLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<BytesHelperLib> {
    return super.deploy(overrides || {}) as Promise<BytesHelperLib>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): BytesHelperLib {
    return super.attach(address) as BytesHelperLib;
  }
  override connect(signer: Signer): BytesHelperLib__factory {
    return super.connect(signer) as BytesHelperLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BytesHelperLibInterface {
    return new utils.Interface(_abi) as BytesHelperLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BytesHelperLib {
    return new Contract(address, _abi, signerOrProvider) as BytesHelperLib;
  }
}
