/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ZRC20Errors,
  ZRC20ErrorsInterface,
} from "../../../../../../@zetachain/protocol-contracts/contracts/zevm/ZRC20.sol/ZRC20Errors";

const _abi = [
  {
    inputs: [],
    name: "CallerIsNotFungibleModule",
    type: "error",
  },
  {
    inputs: [],
    name: "GasFeeTransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidSender",
    type: "error",
  },
  {
    inputs: [],
    name: "LowAllowance",
    type: "error",
  },
  {
    inputs: [],
    name: "LowBalance",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroGasCoin",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroGasPrice",
    type: "error",
  },
] as const;

export class ZRC20Errors__factory {
  static readonly abi = _abi;
  static createInterface(): ZRC20ErrorsInterface {
    return new Interface(_abi) as ZRC20ErrorsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ZRC20Errors {
    return new Contract(address, _abi, runner) as unknown as ZRC20Errors;
  }
}
