/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iGatewayZevmSol from "./IGatewayZEVM.sol";
export * as izrc20Sol from "./IZRC20.sol";
export * as universalContractSol from "./UniversalContract.sol";
export { ICoreRegistry__factory } from "./ICoreRegistry__factory";
