/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IZRC20__factory } from "./IZRC20__factory";
export { ZContract__factory } from "./ZContract__factory";
