/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iGatewayZevmSol from "./IGatewayZEVM.sol";
export * as iwzetaSol from "./IWZETA.sol";
export * as izrc20Sol from "./IZRC20.sol";
export * as universalContractSol from "./UniversalContract.sol";
export { ISystem__factory } from "./ISystem__factory";
