/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iGatewayZevmSol from "./IGatewayZEVM.sol";
export type { iGatewayZevmSol };
import type * as izrc20Sol from "./IZRC20.sol";
export type { izrc20Sol };
import type * as universalContractSol from "./UniversalContract.sol";
export type { universalContractSol };
export type { ICoreRegistry } from "./ICoreRegistry";
