name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build
